# Copyright (c) 2023-2024 Geosiris.
# SPDX-License-Identifier: Apache-2.0
"""STL export (binary and ASCII), triangles only."""

from __future__ import annotations

import logging
import struct
from typing import TYPE_CHECKING, Any, List, Optional, BinaryIO

import numpy as np

from energyml.utils.data.export._base import (
    ExportFormat,
    resolve_origin_shift,
    STLExportOptions,
    _get_export_points,
    _get_faces_or_cells,
    _normalize_to_patches,
    _parse_vtk_flat_faces,
)

from energyml.utils.data.export._registry import FormatSpec, register_format

if TYPE_CHECKING:
    from energyml.utils.data.crs import PointFrame

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# STL export
# ---------------------------------------------------------------------------


def export_stl(
    mesh_list: Any,
    out: BinaryIO,
    options: Optional[STLExportOptions] = None,
    use_crs_displacement: bool = True,
    frame: Optional["PointFrame"] = None,
    origin_shift: Optional[Any] = None,
    use_network: bool = False,
) -> None:
    """Export triangulated mesh data to STL format (binary or ASCII).

    Non-triangular polygons are fan-triangulated (vertex 0 + consecutive pairs).
    Polylines and point sets are silently skipped.

    :param mesh_list: Meshes to export.
    :param out: Binary output stream.
    :param options: STL export options.
    :param use_crs_displacement: Apply CRS displacement to ``NumpyMesh`` points.
    """
    from energyml.utils.data.mesh import SurfaceMesh
    from energyml.utils.data.mesh_numpy import NumpyMesh, NumpyPolylineMesh, NumpyPointSetMesh

    if options is None:
        options = STLExportOptions(binary=True)

    patches = _normalize_to_patches(mesh_list)
    # STL carries no colour / context; workspace not needed unless CRS is requested.
    workspace = None  # CRS requires a workspace — callers may read with CRS pre-applied.
    _origin_shift = resolve_origin_shift(patches, use_crs_displacement, workspace, frame, origin_shift, use_network)

    all_triangles: List[tuple] = []

    for mesh in patches:
        if isinstance(mesh, (NumpyPolylineMesh, NumpyPointSetMesh)):
            continue  # STL is surface-only
        pts, _pts_frame, _ = _get_export_points(
            mesh, use_crs_displacement, workspace, frame, _origin_shift, use_network
        )
        pts_np = np.asarray(pts, dtype=np.float64).reshape(-1, 3)

        if isinstance(mesh, NumpyMesh):
            face_list = _parse_vtk_flat_faces(_get_faces_or_cells(mesh))
        else:
            if not isinstance(mesh, SurfaceMesh):
                continue
            face_list = mesh.get_indices()

        for face in face_list:
            face = list(face)
            if len(face) < 3:
                continue
            if len(face) == 3:
                all_triangles.append((pts_np[face[0]], pts_np[face[1]], pts_np[face[2]]))
            else:
                # Fan triangulation for quads and polygons
                for j in range(1, len(face) - 1):
                    all_triangles.append((pts_np[face[0]], pts_np[face[j]], pts_np[face[j + 1]]))

    if options.binary:
        _export_stl_binary(all_triangles, out)
    else:
        _export_stl_ascii(all_triangles, out, options.ascii_precision)


def _compute_normal(p0: np.ndarray, p1: np.ndarray, p2: np.ndarray) -> np.ndarray:
    v1, v2 = p1 - p0, p2 - p0
    n = np.cross(v1, v2)
    norm = np.linalg.norm(n)
    return n / norm if norm > 0 else np.zeros(3)


def _export_stl_binary(triangles: List[tuple], out: BinaryIO) -> None:
    header = b"Binary STL file generated by energyml-utils" + b"\0" * (80 - 44)
    out.write(header)
    out.write(struct.pack("<I", len(triangles)))
    for p0, p1, p2 in triangles:
        normal = _compute_normal(p0, p1, p2)
        out.write(struct.pack("<fff", *normal.tolist()))
        for pt in (p0, p1, p2):
            out.write(struct.pack("<fff", float(pt[0]), float(pt[1]), float(pt[2])))
        out.write(struct.pack("<H", 0))


def _export_stl_ascii(triangles: List[tuple], out: BinaryIO, precision: int) -> None:
    out.write(b"solid mesh\n")
    for p0, p1, p2 in triangles:
        normal = _compute_normal(p0, p1, p2)
        out.write(
            f"  facet normal {normal[0]:.{precision}e} {normal[1]:.{precision}e} {normal[2]:.{precision}e}\n".encode()
        )
        out.write(b"    outer loop\n")
        for pt in (p0, p1, p2):
            out.write(f"      vertex {pt[0]:.{precision}e} {pt[1]:.{precision}e} {pt[2]:.{precision}e}\n".encode())
        out.write(b"    endloop\n  endfacet\n")
    out.write(b"endsolid mesh\n")


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------


def _write(
    mesh_list: Any,
    out: BinaryIO,
    *,
    obj_name: Optional[str] = None,
    options: Any = None,
    contexts: Any = None,
    use_crs_displacement: bool = True,
    frame: Optional["PointFrame"] = None,
    origin_shift: Optional[Any] = None,
    companion: Any = None,
) -> None:
    """Uniform adapter used by the registry; STL carries no colour context."""
    export_stl(
        mesh_list,
        out,
        options,
        use_crs_displacement,
        frame=frame,
        origin_shift=origin_shift,
    )


register_format(
    FormatSpec(
        format=ExportFormat.STL,
        description="STL — stereolithography (triangles only)",
        filter_label="STL Files (*.stl)",
        writer=_write,
        binary=True,
        options_class=STLExportOptions,
        supports_lines=False,
        supports_pointsets=False,
    )
)
